version: "2"
services:
  docker-registry:
    image: registry:2
    container_name: docker-registry
    volumes:
      - /opt/docker/registry/data:/tmp/registry-dev

  docker-registry-proxy:
    image: ppcelery/docker-registry-proxy
    container_name: docker-registry-proxy
    ports:
      - "443:443"
    links:
      - docker-registry:docker-registry
    volumes:
      - /etc/nginx/conf.d:/etc/nginx/conf.d
      - ./keys:/etc/nginx/ssl:ro

networks:
  default:
    driver: bridge
