version: "2"
services:
  docker-registry:
    image: registry:2
    container_name: docker-registry
    ports:
      - "5000:5000"
    volumes:
      - /opt/docker/registry/data:/tmp/registry-dev

  docker-registry-proxy:
    image: ppcelery/docker-registry-proxy
    container_name: docker-registry-proxy
    ports:
      - "443:443"
    environment:
      - REGISTRY_HOST=docker-registry
      - REGISTRY_PORT=5000
      - BUILDER_IP=10.47.12.82
    links:
      - docker-registry:docker-registry
    volumes:
      - ./keys:/etc/nginx/ssl:ro

networks:
  default:
    driver: bridge
