version: "2"
services:
  docker-registry:
    image: registry:2
    restart: always
    volumes:
      - /var/lib/registry:/var/lib/registry

  docker-registry-proxy:
    image: ppcelery/docker-registry-proxy
    restart: always
    ports:
      - "443:443"
    links:
      - docker-registry:docker-registry
    volumes:
      - /etc/nginx/conf.d:/etc/nginx/conf.d
      - ./keys:/etc/nginx/ssl:ro

  registry-ui:
    image: konradkleine/docker-registry-frontend:v2
    restart: always
    ports:
      - 80:80
    links:
      - docker-registry:registry
    environment:
      ENV_MODE_BROWSE_ONLY: "false"
      ENV_DOCKER_REGISTRY_HOST: registry
      ENV_DOCKER_REGISTRY_PORT: 5000

networks:
  default:
    driver: bridge